### PR TITLE
Implement the Display trait for BitVec

### PR DESCRIPTION
**Pull request by wyhaya**

### CODE REVIEW

**Comment by pczarn** [comment]
Hey,

* The code was wrong, and the problem remains: `Debug` should output stuff like `BitVec { storage: 11010101001100000, nbits: 15 }`
* A better impl for Display is `f.write_char(if bit { '1' } else { '0' })`

**Comment by pczarn** [comment]
best to make it `BitVec { storage: 11010101001100000, padding: 0, nbits: 15 }`

**Comment by wyhaya** [comment]
```rs
fn main() {
    let mut bits = BitVec::new();
    for i in 0..10 {
        bits.push(i % 2 == 0);
    }

    println!("{}", bits);
    // 1010101010

    dbg!(bits);
    // bits = BitVec {
    //     storage: 1010101010,
    //     nbits: 10,
    // }
}
```
@pczarn I haven't added `padding` yet, I'm not quite sure if we should display the full `BitBlock` in `storage`, but I think it's already good enough, could you take another look? Thanks.

**Comment by pczarn** [comment]
Please do it this way

`BitVec { storage: "10101010101010101010101010101010 10101010 000000000000000000", nbits: 15 }`

The spaces separate bit blocks and also mark the beginning of the padding in the last block.

Also, storage is shown as a string so that it looks similar to real code.

**Comment by pczarn** [comment]
The quotes truly are needed because the current code outputs stuff like `BitVec { storage: , nbits: 0 }`

**Comment by wyhaya** [comment]
@pczarn Thanks, I have restored the code, and this PR only implements the `Display` trait without making any changes to the `Debug` trait, and modifying the Debug implementation is somewhat challenging for me. When I'm ready, I'll recreate a PR.

**Comment by pczarn** [comment]
👍

**Comment by pczarn** [comment]
@wyhaya Please include tests with the next PR.

**Comment by pczarn** [comment]
@wyhaya You know, this code was written 10 years ago, perhaps the Display and Debug traits were still getting made back then.

**Comment by pczarn** [comment]
@wyhaya I can teach you Rust if you're willing to write some code for `bit-vec`.

**Comment by wyhaya** [comment]
Hi, @pczarn I've submitted a debug implementation at #96, not entirely sure if it meets the requirements, could you take a look when you have time? ❤️

**Pull request merged**
