### PR TITLE
Give a better error message when setting out of bounds.

### PR DESCRIPTION
**Pull request by reem**

### CODE REVIEW

**Comment by Gankro** [comment]
Might as well also actually say "index out of bounds"?

**Comment by reem** [comment]
Updated to give an even better message (says index out of bounds, outputs a true inequality)

**Comment by Gankro** [comment]
@Gankro r+ p=1

**Comment by Gankro** [comment]
Yes sir!

Testing...

**Comment by Gankro** [comment]
All tests passed.

:camel:

**Pull request merged**
